{ pkgs, inputs, ... }:
{
  home.packages = with pkgs; [
    bat
    bibata-cursors
    catppuccin-gtk
    (inputs.claude-desktop.packages.${pkgs.system}.claude-desktop-with-fhs)
    dunst
    eza
    fd
    font-awesome
    gnutls
    grim
    grimblast
    hyfetch
    hypridle
    hyprlock
    hyprpaper
    kitty
    lm_sensors
    nerd-fonts.jetbrains-mono
    ripgrep
    slurp
    starship
    vesktop
    waybar
    wl-clipboard
    wofi
    zoxide
    zsh
  ];
} 